version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    network_mode: bridge
    environment:
      MYSQL_DATABASE: 'testDB'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      -  3308:3306
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  item-service:
    image: golang:1.13
    build: .
    network_mode: bridge
    ports:
        - '3348:3348'
    volumes: 
        - .:/go/src/Item-Service
    expose:
      - '3348'
    command: go run /go/src/Item-Service/main.go
    
# Names our volume
volumes:
  my-db: